Add upper bound for http-client
Otherwise building with cabal will fail with the following error:

    In order, the following will be built (use -v for more details):
    telegram-api-0.5.0.1
    Preprocessing library telegram-api-0.5.0.1...
    [1 of 7] Compiling Servant.Client.MultipartFormData ( src/Servant/Client/MultipartFormData.hs, /home/arguggi/projects/myforks/haskell-telegram-api/dist-newstyle/build/telegram-api-0.5.0.1/build/Servant/Client/MultipartFormData.o ) [Servant.Common.Req changed]

    src/Servant/Client/MultipartFormData.hs:63:34: error:
        Not in scope: ‘checkStatus’

Since checkStatus was changed to checkResponse in version 0.5.0.0
(see https://hackage.haskell.org/package/http-client/changelog)